---
repos:
  # https://pycqa.github.io/isort/docs/configuration/black_compatibility.html#integration-with-pre-commit
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
  # Ruff
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.11.12
    hooks:
      - id: ruff
        args: ["--fix"]
  # https://github.com/pre-commit/pre-commit-hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: ['--maxkb=500']
  # Github action
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint
  # https://pyproject-fmt.readthedocs.io/en/latest/
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: "v2.6.0"
    hooks:
      - id: pyproject-fmt
  # codespell
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
  # markdownlint
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.45.0
    hooks:
      - id: markdownlint
        args: ["--disable", "MD041"]
  # yamllint
  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.37.1
    hooks:
      - id: yamllint
        args:
          - "--strict"
          - "-d"
          - >
            {
              extends: default,
              rules: {
                line-length: {max: 300},
                indentation: {spaces: 2, indent-sequences: consistent},
                truthy: {allowed-values: ["true", "false", "on", "off"]}
              }
            }
  # towncrier
  - repo: https://github.com/twisted/towncrier
    rev: 24.8.0
    hooks:
      - id: towncrier-update
        files: ^docs/changes/
        args: ['--keep']
