repos:
  # https://pycqa.github.io/isort/docs/configuration/black_compatibility.html#integration-with-pre-commit
  - repo: https://github.com/pycqa/isort
    rev: 6.0.1
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args: ["--line-length=100"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff
    rev: v0.11.4
    hooks:
      - id: ruff
        args: ["--fix"]
  # https://github.com/pre-commit/pre-commit-hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
        args: ['--maxkb=500']
  # https://github.com/HunterMcGushion/docstr_coverage
#  - repo: https://github.com/HunterMcGushion/docstr_coverage
#    rev: v2.3.2  # most recent docstr-coverage release or commit sha
#    hooks:
#      - id: docstr-coverage
#        args: ["--verbose", "2", "--fail-under", "70.", "v2dl5"]
  # Github action
  - repo: https://github.com/rhysd/actionlint
    rev: v1.7.7
    hooks:
      - id: actionlint
  # https://pyproject-fmt.readthedocs.io/en/latest/
  - repo: https://github.com/tox-dev/pyproject-fmt
    rev: "v2.5.1"
    hooks:
      - id: pyproject-fmt
  # codespell
  - repo: https://github.com/codespell-project/codespell
    rev: v2.4.1
    hooks:
      - id: codespell
