# installation:
# create: mamba env create -f environment.yml
# activate: conda activate v2dl5
# update: mamba env update -f environment.yml --prune
# update (micromamba): micromamba update -f environment.yml
#
name: v2dl5
channels:
  - conda-forge
dependencies:
  - astropy-base
  - astroquery
  - gammapy
  - matplotlib
  - pre-commit
  - pydantic
  - pyflakes
  - pylint
  - pytest
  - pytest-cov
  - pytest-xdist
  - python
  - scipy
  - uproot
